name: Run tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rails
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Set up database
        run: |
          bundle exec rake db:create
          bundle exec rake db:schema:load
          bundle exec rake db:migrate
      - name: Run tests
        run: |
          bundle exec rake assets:precompile
          bundle exec rake test
      - name: Determine code coverage
        uses: codecov/codecov-action@v1
